web/trades/apps/main/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (LoginView, LogoutView,)
from .views import (home, register,
                    view_profile, edit_user_profile, change_password,
                    MyPasswordResetView, MyPasswordResetDoneView,
                    MyPasswordResetConfirmView, MyPasswordResetCompleteView)

app_name = "main"

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'login/$', LoginView.as_view(template_name='main/login.html'), name='login'),
    url(r'^logout/$', LogoutView.as_view(template_name='main/logout.html'), name='logout'),
    url(r'^register/$', register, name='register'),

    url(r'^profile/$', view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', view_profile, name='view_profile_with_pk'),
    url(r'^profile/edit/user/$', edit_user_profile, name='edit_user_profile'),

    url(r'^change-password/$', change_password, name='change_password'),
    url(r'^reset-password/$', MyPasswordResetView.as_view(), name='reset_password'),
    url(r'^reset-password/done/$', MyPasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset-password/complete/$', MyPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

web/trades/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('trades.apps.main.urls')),
    path(r'todo/', include('trades.apps.todo.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/trades/apps/main/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save


class GlobUser(AbstractUser):
    pass


# Users
class UserProfile(models.Model):
    TYPES = (
        (0, 'Staff'),
        (1, 'Student'),
        (2, 'Instructor'),
    )
    user = models.OneToOneField(GlobUser, on_delete=models.CASCADE, primary_key=True)
    description = models.CharField(max_length=100, default='', blank=True)
    city = models.CharField(max_length=100, default='', blank=True)
    country = models.CharField(max_length=100, default='', blank=True)
    website = models.URLField(default='http://JerusalemCollege.org', blank=True)
    phone = models.CharField(max_length=20, default='', blank=True)
    type = models.IntegerField(default=1, choices=TYPES)
    image = models.ImageField(upload_to='main/', default='main/unknown.png')

    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name


# Registrations
def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])
        user_profile.save()


post_save.connect(create_profile, sender=GlobUser)

web/trades/apps/main/forms.py
from django import forms
from django.contrib.auth.forms import (UserCreationForm)
from .models import (GlobUser, UserProfile)


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = GlobUser
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditUserForm(forms.ModelForm):
    class Meta:
        model = GlobUser
        fields = (
            'first_name',
            'last_name',
            'email'
        )


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('description',
                  'city',
                  'country',
                  'website',
                  'phone',
                  'type',
                  'image')

web/trades/apps/main/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.views import (PasswordResetView, PasswordResetDoneView,
                                       PasswordResetConfirmView, PasswordResetCompleteView)
from django.contrib import messages
from .forms import (RegistrationForm, EditUserForm, UserProfileForm)
from .models import (GlobUser)


def home(request):
    title = "Home page for Trading"
    return render(request, 'main/home.html', {'title': title})


def email_message(semail, type):
    if type == 'register':
        email_from = 'noreply@drbaranes.com'
        subject = 'Registration to Trading Program'
        body = 'Your registration has been accepted. Please login and update your profile in Edit your profile.' \
               ' http://127.0.0.1:8010/.'
    elif type == 'instructor_confirmed':
        email_from = 'noreply@drbaranes.com'
        subject = 'Confirmation on instructor status'
        body = 'Your status as instructor has been confirmed. You can create a new games:  http://127.0.0.1:8010/'

    send_mail(subject, body, email_from, [semail], fail_silently=False)


# Registration
def register(request):
    print(request.method)
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            print(cd)
            semail = cd['email']
            email_message(semail, 'register')
            form.save()

            return redirect(reverse('main:home'))
    else:
        form = RegistrationForm()
        args = {'form': form}
        return render(request, 'main/reg_form.html', args)


# Portfolios
def view_profile(request, pk=None):
    if pk:
        user = GlobUser.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'main/profile.html', args)


def edit_user_profile(request):
    if request.method == 'POST':
        # print("edit_user_profile1000: \n\n", request.POST, '\n\n')
        user_form = EditUserForm(instance=request.user, data=request.POST)
        profile_form = UserProfileForm(instance=request.user.userprofile, data=request.POST, files=request.FILES)
        # print("edit_user_profile1001: \n\n", user_form, '\n\n')
        # print("edit_user_profile1001: \n\n", profile_form, '\n\n')
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'User profile updated successfully.')
            return redirect(reverse('main:view_profile'))
    else:
        user_form = EditUserForm(instance=request.user)
        profile_form = UserProfileForm(instance=request.user.userprofile)
        args = {'user_form': user_form, 'profile_form': profile_form}
        return render(request, 'main/edit_user_profile.html', args)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('main:view_profile'))
        else:
            return redirect(reverse('main:change_password'))
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'main/change_password.html', args)


class MyPasswordResetView(PasswordResetView):
    # form_class = PasswordResetForm
    template_name = 'main/reset_password.html'
    success_url = reverse_lazy('main:password_reset_done')
    # subject_template_name = 'accounts/emails/password-reset-subject.txt'
    email_template_name = 'main/reset_password_email.html'


class MyPasswordResetDoneView(PasswordResetDoneView):
    # form_class = PasswordResetForm
    template_name = 'main/reset_password_done.html'


class MyPasswordResetConfirmView(PasswordResetConfirmView):
    # form_class = PasswordResetForm
    template_name = 'main/reset_password_confirm.html'
    success_url = reverse_lazy('main:password_reset_complete')


class MyPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'main/reset_password_complete.html'

web/trades/apps/main/templates/main/change_password.html
{% extends 'base_main.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

web/trades/apps/main/templates/main/edit_profile.html
{% extends 'base_main.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

web/trades/apps/main/templates/main/edit_user_profile.html
{% extends 'base_main.html' %}

{% block head %}
<title>User Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

web/trades/apps/main/templates/main/home.html
{% extends "base_main.html" %}
{% load static %}

{% block body %}
<div><h1> {{ title }} </h1>
</div>
<hr>

<div class="text-center">
  <br>
   <img src="{% static "main/main1.jpeg" %}" width="200" height="200" />
  <br>
</div>

{% endblock body %}

web/trades/apps/main/templates/main/login.html
{% extends 'base_main.html' %}

{% block head %}
    <title>Login</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Welcome</h1>
    <p>
        You can log in here!
    </p>
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</div>
{% endblock %}

web/trades/apps/main/templates/main/logout.html
{% extends 'base_main.html' %}

{% block body %}
<div class="container">
    <h1>Logged out</h1>
    <p>
        You have logged out!
    </p>
</div>
{% endblock %}

web/trades/apps/main/templates/main/profile.html
{% extends 'base_main.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Profile</h1>
    <p>Username: {{ user }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Description: {{ user.userprofile.description }}</p>
    <p>Phone: {{ user.userprofile.phone }}</p>
    <p>City: {{ user.userprofile.city }}</p>
    <p>Country: {{ user.userprofile.country }}</p>
    <p>Website: {{ user.userprofile.website }}</p>
    <p>Institution: {{ user.userprofile.institution }}</p>
    {% if user.userprofile.image %}
    <img src="{{ user.userprofile.image.url }}" width="240">
    {% endif %}
</div>

{% endblock %}

web/trades/apps/main/templates/main/reg_form.html
{% extends 'base_main.html' %}

{% block body %}
<div class="container">
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}

web/trades/apps/main/templates/main/reset_password.html
{% extends 'base_main.html' %}

{% block body %}
<div class="container">
    <h1>Password reset</h1>
    <p>
        Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

web/trades/apps/main/templates/main/reset_password_complete.html
{% extends 'base_main.html' %}

{% block body %}
<div class="container">
    <h1>Password reset complete</h1>
    <a href="{% url 'registration:login' %}">Log in</a>
</div>
{% endblock %}

web/trades/apps/main/templates/main/reset_password_confirm.html
{% extends 'base_main.html' %}

{% block body %}
<div class="container">
    <h1>Enter new password</h1>
    <p>

    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

web/trades/apps/main/templates/main/reset_password_done.html
{% extends 'base_main.html' %}

{% block body %}
<div class="container">
    <h1>Password reset sent</h1>
    <p>
        We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

        If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
    </p>
</div>
{% endblock %}

web/trades/apps/main/templates/main/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'main:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}