web/trades/apps/main/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (LoginView, LogoutView,)
from .views import (home, register,
                    view_profile, edit_user_profile, change_password,
                    MyPasswordResetView, MyPasswordResetDoneView,
                    MyPasswordResetConfirmView, MyPasswordResetCompleteView)

app_name = "main"

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'login/$', LoginView.as_view(template_name='main/login.html'), name='login'),
    url(r'^logout/$', LogoutView.as_view(template_name='main/logout.html'), name='logout'),
    url(r'^register/$', register, name='register'),

    url(r'^profile/$', view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', view_profile, name='view_profile_with_pk'),
    url(r'^profile/edit/user/$', edit_user_profile, name='edit_user_profile'),

    url(r'^change-password/$', change_password, name='change_password'),
    url(r'^reset-password/$', MyPasswordResetView.as_view(), name='reset_password'),
    url(r'^reset-password/done/$', MyPasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset-password/complete/$', MyPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

web/trades/apps/todo/urls.py
from django.conf.urls import url
from .views import (index)

app_name = "todo"

urlpatterns = [
    url(r'^$', index, name='index'),
]

web/trades/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('trades.apps.main.urls')),
    path(r'todo/', include('trades.apps.todo.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/trades/apps/main/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save


class GlobUser(AbstractUser):
    pass


# Users
class UserProfile(models.Model):
    TYPES = (
        (0, 'Staff'),
        (1, 'Student'),
        (2, 'Instructor'),
    )
    user = models.OneToOneField(GlobUser, on_delete=models.CASCADE, primary_key=True)
    description = models.CharField(max_length=100, default='', blank=True)
    city = models.CharField(max_length=100, default='', blank=True)
    country = models.CharField(max_length=100, default='', blank=True)
    website = models.URLField(default='http://JerusalemCollege.org', blank=True)
    phone = models.CharField(max_length=20, default='', blank=True)
    type = models.IntegerField(default=1, choices=TYPES)
    image = models.ImageField(upload_to='main/', default='main/unknown.png')

    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name


# Registrations
def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])
        user_profile.save()


post_save.connect(create_profile, sender=GlobUser)

web/trades/apps/todo/models.py
from django.db import models


class Item(models.Model):
    text = models.TextField(blank=False, null=False)
    date_posted = models.DateField(auto_now=True)

web/trades/apps/main/forms.py
from django import forms
from django.contrib.auth.forms import (UserCreationForm)
from .models import (GlobUser, UserProfile)


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = GlobUser
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditUserForm(forms.ModelForm):
    class Meta:
        model = GlobUser
        fields = (
            'first_name',
            'last_name',
            'email'
        )


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('description',
                  'city',
                  'country',
                  'website',
                  'phone',
                  'type',
                  'image')

web/trades/apps/main/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.views import (PasswordResetView, PasswordResetDoneView,
                                       PasswordResetConfirmView, PasswordResetCompleteView)
from django.contrib import messages
from .forms import (RegistrationForm, EditUserForm, UserProfileForm)
from .models import (GlobUser)


def home(request):
    title = "Home page for Trading"
    return render(request, 'main/home.html', {'title': title})


def email_message(semail, type):
    if type == 'register':
        email_from = 'noreply@drbaranes.com'
        subject = 'Registration to Trading Program'
        body = 'Your registration has been accepted. Please login and update your profile in Edit your profile.' \
               ' http://127.0.0.1:8010/.'
    elif type == 'instructor_confirmed':
        email_from = 'noreply@drbaranes.com'
        subject = 'Confirmation on instructor status'
        body = 'Your status as instructor has been confirmed. You can create a new games:  http://127.0.0.1:8010/'

    send_mail(subject, body, email_from, [semail], fail_silently=False)


# Registration
def register(request):
    print(request.method)
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            print(cd)
            semail = cd['email']
            email_message(semail, 'register')
            form.save()

            return redirect(reverse('main:home'))
    else:
        form = RegistrationForm()
        args = {'form': form}
        return render(request, 'main/reg_form.html', args)


# Portfolios
def view_profile(request, pk=None):
    if pk:
        user = GlobUser.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'main/profile.html', args)


def edit_user_profile(request):
    if request.method == 'POST':
        # print("edit_user_profile1000: \n\n", request.POST, '\n\n')
        user_form = EditUserForm(instance=request.user, data=request.POST)
        profile_form = UserProfileForm(instance=request.user.userprofile, data=request.POST, files=request.FILES)
        # print("edit_user_profile1001: \n\n", user_form, '\n\n')
        # print("edit_user_profile1001: \n\n", profile_form, '\n\n')
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'User profile updated successfully.')
            return redirect(reverse('main:view_profile'))
    else:
        user_form = EditUserForm(instance=request.user)
        profile_form = UserProfileForm(instance=request.user.userprofile)
        args = {'user_form': user_form, 'profile_form': profile_form}
        return render(request, 'main/edit_user_profile.html', args)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('main:view_profile'))
        else:
            return redirect(reverse('main:change_password'))
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'main/change_password.html', args)


class MyPasswordResetView(PasswordResetView):
    # form_class = PasswordResetForm
    template_name = 'main/reset_password.html'
    success_url = reverse_lazy('main:password_reset_done')
    # subject_template_name = 'accounts/emails/password-reset-subject.txt'
    email_template_name = 'main/reset_password_email.html'


class MyPasswordResetDoneView(PasswordResetDoneView):
    # form_class = PasswordResetForm
    template_name = 'main/reset_password_done.html'


class MyPasswordResetConfirmView(PasswordResetConfirmView):
    # form_class = PasswordResetForm
    template_name = 'main/reset_password_confirm.html'
    success_url = reverse_lazy('main:password_reset_complete')


class MyPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'main/reset_password_complete.html'

web/trades/apps/todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from redis import Redis
from .models import (Item)

try:
    redis = Redis(host='redis', port=6379)
except Exception:
    pass


def index(request):
    if request.method == 'POST':
        Item.objects.create(text=request.POST['item_text'])
        # return redirect('/')
    items = Item.objects.all()
    counter = 100
    try:
        counter = redis.incr('counter')
    except Exception:
        pass
    return render(request, 'todo/index.html', {'items': items, 'counter': counter})

web/trades/templates/base.html
<!DOCTYPE html>
<html>
  <head>
      {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0", shrink-to-fit=yes">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
          crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link href="{% static 'styles/style2_bs.css' %}" rel='stylesheet'>
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    <link href="{% static 'styles/site.css' %}" rel='stylesheet'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    {% block title %}
      <title>Base</title>
    {% endblock title%}
  </head>
  <body>
    <div class="wrapper">
      <nav id="sidebar">
        <div class="sidebar-header">
          <a href="/" ><h5>
              <img src="{% static "main/option_logo.jpg" %}"
              alt="My image"  height="40" width="60">
              OptionTrading
          </h5></a>
              {{ user.first_name }} {{ user.last_name }}
        </div>

        {% if user.is_authenticated %}
            <!--Staff -->
            {% if user.is_staff %}
                <h6>Staff</h6>
                <ul class="list-unstyled components">
                    <li class="active">
                        <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false"
                           class="dropdown-toggle">List Example</a>
                        <ul class="collapse list-unstyled" id="homeSubmenu">
                            <li>
                                <a href="#">List 1</a>
                            </li>
                            <li>
                                <a href="#">List 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="{% static "doc/ToDo List.docx" %}" class="download">ToDo</a>
                    </li>
                </ul>
            {% else %}
                    <!-- Student -->
                    <ul class="list-unstyled components">
                        <li>
                            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Example Reports</a>
                            <ul class="collapse list-unstyled" id="pageSubmenu">
                                <li>
                                    <a href="#">R&D</a>
                                </li>
                                <li>
                                    <a href="#">Marketing</a>
                                </li>
                                <li>
                                    <a href="#">Operations</a>
                                </li>
                                <li>
                                    <a href="#">Finance</a>
                                </li>
                            </ul>
                        </li>

                        <!-- Portfolio -->
                        <li>
                            <a href="#profileSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Portfolio</a>
                            <ul class="collapse list-unstyled" id="profileSubmenu">
                                <li>
                                    <a href="{% url 'main:view_profile' %}">View Profile</a>
                                    <a href="{% url 'main:edit_user_profile' %}">Edit User Profile</a>
                                    <hr/>
                                    <a href="{% url 'main:change_password' %}">Change Password</a>
                                    <a href="{% url 'main:reset_password' %}">Reset Password<</a>
                                </li>
                            </ul>
                        </li>

                        <li>
                            <a href="#">About</a>
                        </li>
                        <li>
                            <a href="#">Contact</a>
                        </li>
                    </ul>
            {% endif %}
         {% else %}
            <ul class="list-unstyled components">
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Example Home</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="#">Home A</a>
                        </li>
                        <li>
                            <a href="#">Home B</a>
                        </li>
                        <li>
                            <a href="#">Home C</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
         {% endif %}
            <ul class="list-unstyled CTAs">
                <li>
                    <a href="{% static "doc/Registrations.docx" %}" class="download">How to register</a>
                </li>
            </ul>
      </nav>
        <!-- Page Content  -->
      <div id="content">

        <!-- ToolBar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            <button type="button" id="sidebarCollapse" class="btn btn-info">
                <i class="fas fa-align-left"></i>
                <!-- <span>Toggle Sidebar</span>  -->
            </button>

            <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button"
                    data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-align-justify"></i>
            </button>

            <!-- Login;  Log off -->
            {% if user.is_authenticated %}
            <ul class="nav navbar-nav navbar-right">
                {% block app_toolbar %}
                {% endblock app_toolbar %}
                {% block sub_app_toolbar %}
                {% endblock sub_app_toolbar %}
              <li><a class="nav-link" href="{% url 'main:logout' %}">Log off</a></li>
            </ul>
            {% else %}
            </ul>
              <!-- Logging -->
            <ul class="nav navbar-nav navbar-right">
              <li><a class="nav-link" href="{% url 'main:login' %}">Log in</a></li>
              <li><a class="nav-link" href="{% url 'main:register' %}">Register</a></li>
              <li><a class="nav-link" href="{% url 'main:reset_password' %}">Reset Password</a></li>
            </ul>
            {% endif %}
          </div>
        </nav>

        <!-- Page body Content  -->

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <il class="{{ message.tages }}">
                    {{ message|safe }}
                    <a href="/" class="close">X</a>
                </il>
                {% endfor %}
            </ul>
        {% endif %}
        {% block body %}
            <h1>Base_bs</h1>
        {% endblock %}
      </div>
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous">
    </script>
    <!-- Optional JavaScript -->
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
            integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
            integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar, #content').toggleClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>
  </body>
</html>